### ISSUE TITLE
新版客户端登陆后报错：未成功获取地址簿

### ISSUE THREAD

**Issue by cleloo** [v5star/rustdesk-api#1]
能够登陆成功，之前的地址簿能获取出来，但是会一直有个报错：未成功获取地址簿：false
可以试一下最新的客户端复现一下

**Comment by mizb** [comment]
我也一样的问题。

**Comment by v5star** [comment]
新版的客户端，获取地址簿是用get,更新地址簿是post，都用调用同一个方法，所以你们自己改的时候，注意一下。我写的有注释。

**Comment by v5star** [comment]
获取新版本即可解决

**Comment by cleloo** [comment]
感谢更新，去测试看看，有问题再来反馈

**Comment by cleloo** [comment]
> 获取新版本即可解决

感谢更新，去测试看看，有问题再来反馈

**Comment by vaalimusic** [comment]
Version 1.2.2 has the same error, can I somehow fix it?

**Comment by cleloo** [comment]
> Version 1.2.2 has the same error, can I somehow fix it?

Just get the new version of the API and redeploy it.

**Comment by v5star** [comment]
> > Version 1.2.2 has the same error, can I somehow fix it?
> 
> Just get the new version of the API and redeploy it.

Check out the latest version and test it. If there is a problem, take screenshots.

**Comment by vaalimusic** [comment]
Hello! This is the error:
![image](https://github.com/v5star/rustdesk-api/assets/63344403/504dfaaf-3e6b-47be-bb68-bbb040184198)

**Comment by cleloo** [comment]
> Check out the latest version and test it. If there is a problem, take screenshots.

Please confirm if the database has been prompted for successful creation, and then log in to the account again

**Comment by vaalimusic** [comment]
> > Check out the latest version and test it. If there is a problem, take screenshots.
> 
> Please confirm if the database has been prompted for successful creation, and then log in to the account again

Here are the screenshots, the last one shows that an error appears when adding. Version 1.2.2 php 7.4

![image](https://github.com/v5star/rustdesk-api/assets/63344403/c6b279aa-d224-48e5-80b2-409470b4ff6f)
![image](https://github.com/v5star/rustdesk-api/assets/63344403/41595c98-e0ab-49c2-a9f4-54fc1db88f25)
![image](https://github.com/v5star/rustdesk-api/assets/63344403/c2db273a-1742-4c24-8aa8-9888bd923347)

**Comment by cleloo** [comment]
> > > Check out the latest version and test it. If there is a problem, take screenshots.
> > 
> > 
> > Please confirm if the database has been prompted for successful creation, and then log in to the account again
> 
> Here are the screenshots, the last one shows that an error appears when adding. Version 1.2.2 php 7.4
> 
> ![image](https://user-images.githubusercontent.com/63344403/270525030-c6b279aa-d224-48e5-80b2-409470b4ff6f.png) ![image](https://user-images.githubusercontent.com/63344403/270525101-41595c98-e0ab-49c2-a9f4-54fc1db88f25.png) ![image](https://user-images.githubusercontent.com/63344403/270525208-c2db273a-1742-4c24-8aa8-9888bd923347.png)
![image](https://github.com/v5star/rustdesk-api/assets/120089289/e64f1a4a-3ee4-4022-83e6-39794a449700)
Log in to your account again

**Comment by vaalimusic** [comment]
> > > > Check out the latest version and test it. If there is a problem, take screenshots.
> > > 
> > > 
> > > Please confirm if the database has been prompted for successful creation, and then log in to the account again
> > 
> > 
> > Here are the screenshots, the last one shows that an error appears when adding. Version 1.2.2 php 7.4
> > ![image](https://user-images.githubusercontent.com/63344403/270525030-c6b279aa-d224-48e5-80b2-409470b4ff6f.png) ![image](https://user-images.githubusercontent.com/63344403/270525101-41595c98-e0ab-49c2-a9f4-54fc1db88f25.png) ![image](https://user-images.githubusercontent.com/63344403/270525208-c2db273a-1742-4c24-8aa8-9888bd923347.png)
> > ![image](https://user-images.githubusercontent.com/120089289/270525594-e64f1a4a-3ee4-4022-83e6-39794a449700.png)
> > Log in to your account again

I re-login to my account but the error does not go away

**Comment by cleloo** [comment]
> > > > > Check out the latest version and test it. If there is a problem, take screenshots.
> > > > 
> > > > 
> > > > Please confirm if the database has been prompted for successful creation, and then log in to the account again
> > > 
> > > 
> > > Here are the screenshots, the last one shows that an error appears when adding. Version 1.2.2 php 7.4
> > > ![image](https://user-images.githubusercontent.com/63344403/270525030-c6b279aa-d224-48e5-80b2-409470b4ff6f.png) ![image](https://user-images.githubusercontent.com/63344403/270525101-41595c98-e0ab-49c2-a9f4-54fc1db88f25.png) ![image](https://user-images.githubusercontent.com/63344403/270525208-c2db273a-1742-4c24-8aa8-9888bd923347.png)
> > > ![image](https://user-images.githubusercontent.com/120089289/270525594-e64f1a4a-3ee4-4022-83e6-39794a449700.png)
> > > Log in to your account again
> 
> I re-login to my account but the error does not go away

![image](https://github.com/v5star/rustdesk-api/assets/120089289/18362d28-00a6-46f3-8801-1d336fc9af2a)
Please change to your server address. If it is arranged within a local area network, please change to a local area network IP address

**Comment by vaalimusic** [comment]
> > > > > > Check out the latest version and test it. If there is a problem, take screenshots.
> > > > > 
> > > > > 
> > > > > Please confirm if the database has been prompted for successful creation, and then log in to the account again
> > > > 
> > > > 
> > > > Here are the screenshots, the last one shows that an error appears when adding. Version 1.2.2 php 7.4
> > > > ![image](https://user-images.githubusercontent.com/63344403/270525030-c6b279aa-d224-48e5-80b2-409470b4ff6f.png) ![image](https://user-images.githubusercontent.com/63344403/270525101-41595c98-e0ab-49c2-a9f4-54fc1db88f25.png) ![image](https://user-images.githubusercontent.com/63344403/270525208-c2db273a-1742-4c24-8aa8-9888bd923347.png)
> > > > ![image](https://user-images.githubusercontent.com/120089289/270525594-e64f1a4a-3ee4-4022-83e6-39794a449700.png)
> > > > Log in to your account again
> > 
> > 
> > I re-login to my account but the error does not go away
> 
> ![image](https://user-images.githubusercontent.com/120089289/270526131-18362d28-00a6-46f3-8801-1d336fc9af2a.png) Please change to your server address. If it is arranged within a local area network, please change to a local area network IP address

I changed it, but unfortunately it didn’t help. Any more ideas what could be the problem?

![image](https://github.com/v5star/rustdesk-api/assets/63344403/ff6794b1-f634-46b6-aff8-232e3bc92c48)
![image](https://github.com/v5star/rustdesk-api/assets/63344403/35110590-696b-42d0-ac5c-6b363432e7be)

**Comment by cleloo** [comment]
Can you confirm again if the generated database tables are working properly, and are the RustDesk version and index. php the latest? Being able to log in to the account indicates that I can access the API, but I have not been able to obtain the information in the data table normally. I have deployed it locally and on the server without any issues.

**Comment by vaalimusic** [comment]
> Can you confirm again if the generated database tables are working properly, and are the RustDesk version and index. php the latest? Being able to log in to the account indicates that I can access the API, but I have not been able to obtain the information in the data table normally. I have deployed it locally and on the server without any issues.

I'm using your latest code.

Authorization works for me, and in version 1.2.2 errors appear as in the screenshot.

There are no errors in Version 1.2.0, but the tags and computers added to the address book after relogin disappear and are not added to the database.

**Comment by v5star** [comment]
> There are no errors in Version 1.2.0, but the tags and computers added to the address book after relogin disappear and are not added to the database.

Version 1.2.0 uses post to get the address book, which is depressing. It is recommended to use version 1.2.2 or above.

**Comment by vaalimusic** [comment]
> > There are no errors in Version 1.2.0, but the tags and computers added to the address book after relogin disappear and are not added to the database.
> 
> Version 1.2.0 uses post to get the address book, which is depressing. It is recommended to use version 1.2.2 or above.

I don't understand anything. I even rewrote the code for mysql and after authorization I still got an error in receiving the address book. Same error from the phone and on other computers. I deployed it on a foreign server and nothing changes. Tell me, can you send a database dump with at least 1 added fake device in the address book?

**Comment by vaalimusic** [comment]
> > I don't understand anything. I even rewrote the code for mysql and after authorization I still got an error in receiving the address book. Same error from the phone and on other computers. I deployed it on a foreign server and nothing changes. Tell me, can you send a database dump with at least 1 added fake device in the address book?
> 
> If you use mysql, I wrote a version last year that supports rustdesk v1.1.9, you can refer to it and modify it. I will update it to github later. the old version api down from https://v5star.lanzouv.com/iCkiB0g642xc ，Password: 52pj

Thanks, I'll try.

I found out here: From the logs it is clear that the SQL query to search for a token is executed with an empty access_token value, which is the cause of the “Access token not found” error. This means that the $auth_token variable does not contain the correct token when executing the SQL query.

Any ideas on this matter, maybe this information will help somehow?
