### ISSUE TITLE
请问用了api服务后，原来的key是否还可以照常连接

### ISSUE THREAD

**Issue by pope-L** [v5star/rustdesk-api#7]
请问用了id服务后，原来的key是否还可以照常连接？
就是不登录，用回原来的key

**Comment by v5star** [comment]
用了ID服务器就等于认证都换了，原来的key会有变动

**Comment by pope-L** [comment]
不好意思，我其实标题写错了，应该是api服务
我看大家普遍都说用api服务器后，加key连接慢，都不填key，服务端也不加-k，
那这样会不会存在某个情况 别人只填id服务，不填api服务器地址，也能使用？

**Comment by v5star** [comment]
可以的，这个api与key没有必然的联系，原作者的话的意思是，有key是加密连接，不填key，也是正常连接的

**Comment by pope-L** [comment]
我试了一下，开启api服务后，客户端不登录也能用，可能开源版本的rustdeskserver就没这个功能了

**Comment by v5star** [comment]
我做这个只是为了方便记忆和管理现有设备ID，不用自己记那么多ID和密码，直接双击就可以连接远程电脑，如说明中的最后一个图，仅此附子功能而已，用不用我这个api服务，原本的rusudesk都正常使用。部署我这个api也不会改变rusudesk原生功能。

**Comment by pope-L** [comment]
明白了  感谢您回复
祝您龙年事事大顺 身体健康
